### ISSUE TITLE
Packet timestamps are off when compared to System.currentTimeMillis()

### ISSUE THREAD

**Issue by aichemzee** [vproxy-tools/Divert-Java#1]
Hi I was trying to get the packet timestamp using `ctx.addr.getTimestamp()`. The value returned was `5185581544175`.
However System.currentTimeMillis() gave me a ts of `1715768564651`. We probably need to convert the timestamp to unix format to prevent the users from being misled. Or add this to javadoc.

**Comment by wkgcass** [comment]
I'll look into the Divert code to see what the timestamp represents

**Comment by aichemzee** [comment]
From Divert it looks like the timestamp on the address is the one that is there on the incoming packet:
https://github.com/basil00/Divert/blob/master/sys/windivert.c#L2268

And it is populated by https://github.com/basil00/Divert/blob/master/sys/windivert.c#L4053C17-L4053C57

Some doc around [KeQueryPerformanceCounter](https://learn.microsoft.com/en-us/windows/win32/sysinfo/acquiring-high-resolution-time-stamps)

A bit unsure about how this would translate to a unix timestamp.

**Comment by aichemzee** [comment]
Some doc around [KeQueryPerformanceCounter](https://learn.microsoft.com/en-us/windows/win32/sysinfo/acquiring-high-resolution-time-stamps)

**Comment by wkgcass** [comment]
Looks like `KeQueryPerformanceCounter` is not an offset to a specific time, but the performance counter ticks.

https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-kequeryperformancecounter  
> KeQueryPerformanceCounter returns the performance counter value in units of ticks.

The retrieved value divided by [QueryPerformanceFrequency](https://learn.microsoft.com/en-us/windows/win32/api/profileapi/nf-profileapi-queryperformancefrequency) would result in a duration of time.

I can provide some helper functions in `RcvSndCtx`, e.g. `ctx.getDeltaTicks()` and `ctx.getDeltaTimestamp()`, which returns `0` for the first received packet, and a delta value for the following packets.

**Comment by aichemzee** [comment]
`ctx.getDeltaTimestamp()` would be helpful I think. If we get milliseconds since the first packet that would be helpful.

**Comment by wkgcass** [comment]
upgrade to version `1.1.0`:

```java
long millis = ctx.getDeltaTimestampMillis();
long nanos = ctx.getDeltaTimestampNanos();
```
